version: '2'
services:
  register-app:
    image: register
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=register-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9821:9821
  register-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: register-cassandra
  register-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=register-cassandra
  register-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: register-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
